config/routes.rb
SorceryPostgresql::Application.routes.draw do
  
  root to: "restaurants#index"
  resources :users do
    resources :reservations, :except => [:new]
  end

  resources :restaurants do
    resources :reservations
  end

  resources :user_sessions, :only => [:new, :create, :destroy]

  get "login" => "user_sessions#new", :as => :login
  get "logout" => "user_sessions#destroy", :as => :logout
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.role == "owner"
        can :manage, :all
    elsif user.role == "customer"
        can :manage, User
        can :manage, Reservation
        can :read, Restaurant
    else
        can :read, Restaurant
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  GUESTS = %w(1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20)
  belongs_to :user
  belongs_to :restaurant
  validates_presence_of :day, :message => "What day would you like to make your reservation?"
  validates_presence_of :time, :message => "What time would you like to make your reservation?"
  validates_presence_of :guests, :message => "How many guests is this for?"
  before_save :availability?


  def capacity
    100
  end

  def availability?
    (booked_guests_at_time + self.guests) <= capacity
  end

  def seats_left
    capacity - booked_guests_at_time
  end

  def booked_guests_at_time
    Reservation.where(restaurant_id: self.restaurant_id, day: self.day, time: self.time).sum(:guests)
  end
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  belongs_to :user
  has_many :reservations
  geocoded_by :address
  after_validation :geocode

  # to define.  Interval, open time, close time. Total people per interval.
end

app/models/user.rb
class User < ActiveRecord::Base
  ROLES = %w(customer owner)
  has_many :restaurants
  has_many :reservations
  authenticates_with_sorcery!

  validates :password, confirmation: true
  validates_presence_of :email
  validates_uniqueness_of :email

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :require_login

  private
  def not_authenticated
    redirect_to login_path, alert: "Please log in first"
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_filter :load_restaurant

  def new
    @reservation = @restaurant.reservations.build
  end

  def create
    @reservation = @restaurant.reservations.build (reservation_params)
    @reservation.user_id = current_user.id
    if @reservation.save
      current_user.loyalty_points += 100
      current_user.save
      redirect_to restaurant_reservation_path(@restaurant.id, @reservation.id)
    else
      unless @reservation.availability?
        flash[:alert] = "Sorry, we can't handle that many people at that time, there are #{@reservation.seats_left} available seats."
      end
      render :new
    end
  end

  def show
    @reservation = @restaurant.reservations.find(params[:id])
  end
  
  private
  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def reservation_params
    params.require(:reservation).permit(:day, :time, :guests)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  skip_before_filter :require_login, except: [:new]
  before_filter :load_user

  def index
    @restaurants= Restaurant.all
  end
  
  def show
    @restaurant = Restaurant.find(params[:id])
  end
  
  def new
    @restaurant = @user.restaurants.build
  end
  
  def edit
    
  end
  
  def create
    @restaurant = @user.restaurants.build restaurant_params
    @restaurant.user_id = current_user.id
    if @restaurant.save
      redirect_to restaurant_path(@restaurant.id)
    else
      render 'new'
    end
  end
  
  
  def update
    
  end
  
  def destroy
    
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :neighbourhood)
  end

  def load_user
    @user = current_user
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:login, :destroy]

  def new
    @user = User.new
  end

  def create
    if @login = login(params[:email], params[:password])
      redirect_back_or_to root_path, :notice => "Logged in"
    else
      flash.now[:alert] = "Login failed"
      render action: "new"
    end
  end

  def destroy
    logout
    redirect_to root_path, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, only: [:index, :new, :create]

  def index
    
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def edit
    
  end
  
  def create
    @user = User.new user_params
    if @user.save
       redirect_to @user, notice: "User successfully created"
    else
      render 'new'
    end
  end
  
  
  def update
    
  end
  
  def destroy
    
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :role)    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def open_time
    11
  end

  def close_time
    20
  end

  def interval
    30.minutes
  end

  def reservation_slots
    reservations = Array.new
    time = DateTime.now.at_beginning_of_day + open_time.hours
    while time.hour.hours <= close_time.hours
      reservations << legible_time(time)
      time += interval
    end
    return reservations
  end

  def legible_time(date_time)
    matchd = /\d{2}:\d{2}:/.match(date_time.to_s)
    matchd = matchd.to_s.split('')
    matchd.pop
    if matchd[0] == 0
      matchd.shift
      return matchd.join('') + " am"
    elsif matchd[0..1].join('').to_i < 12
      return matchd.join('') + " am"
    elsif matchd[0..1].join('').to_i == 12
      return matchd.join('') + " pm"
    else
      return (matchd[0..1].join('').to_i - 12).to_s + matchd[2..-1].join('') + " pm"
    end
  end

  def this_week?(reservation)
    !(reservation.day.past? || reservation.day > (Date.today + 7.days))
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def your_customers(user)
    yr_restos = user.restaurants
    yr_customers = Array.new
    yr_restos.each do |resto|
      resto.reservations.each do |reserv_set|
        yr_customers << User.find(reserv_set.user_id)
      end
    end
    yr_customers.uniq
  end
end

app/views/layouts/_nav_bar.html.erb
<nav class="top-bar">
   <ul class="title-area">
     <li class="name">
        <h1><a href="<%= root_path %>">Seat Your Self</a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
   </ul>

   <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      
      <% if current_user %>
        <li><a href="<%= user_path(current_user) %> ">Your Profile</a></li>
        <li class="divider"></li>
        <li><a href="<%= logout_path %> ">Log out</a></li>
      <% else %>
        <li><a href="<%= login_path %> ">Log in</a></li>
        <li class="divider"></li>
        <li><a href="<%= new_user_path %> ">Sign up</a></li>
      <% end %>
     </ul>
   </section>
      
 </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render "layouts/nav_bar" %>
    <% if flash[:alert] %>
      <div class="alert">
        <%= flash[:alert] %>
      </div>
    <% end %>
    <% if flash[:notice] %>
      <div class="notice">
        <%= flash[:notice] %>
      </div>
    <% end %>
      
    <div class="row">
      <div class="large-12 large-centered columns">
        <div class="large-8 large-centered columns">
          <%= yield %>
        </div>
      </div>
    </div>  
    

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/reservations/_search_results.html.erb
<h1>HI!</h1>

app/views/reservations/new.html.erb
<h2>Make a reservation</h2>
<p><%= link_to Restaurant.find(params[:restaurant_id]).name, restaurant_path(params[:restaurant_id]) %></p>

<%= form_for @reservation, url: {:action => "create"} do |f| %>
  <% if @reservation.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @reservation.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :day %>
  <%= f.date_field :day %>
  <br>
  <%= f.label :time %>
  <%= f.collection_select :time, reservation_slots, :to_s, :humanize %>
  <br>
  <%= f.label :guests %>
  <%= f.collection_select :guests, Reservation::GUESTS, :to_i, :humanize %>
  
  <%= f.submit "Take a seat", :class => "button" %>
<% end %>

app/views/reservations/search.html.erb
<%= form_for @reservation, url: {action: "search"} do |f| %>
  <% if @reservation.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @reservation.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :day %>
  <%= f.text_field :day %>
  <br>
  <%= f.label :time %>
  <%= f.text_field :time %>
  <br>
  <%= f.label :guests %>
  <%= f.text_field :guests %>
  <br>
  <%= f.submit "Find a seat!", :class => "button" %>
<% end %>

<% if @reservations != nil %>
  <%= render "search_results" %>
<% end %>
  

app/views/reservations/show.html.erb
<p>Reservation successfully made at <%= @restaurant.name %>!</p>
<br>  
<p>Your reservation is for <%= @reservation.time %></p>
<br>  
<p>Reservation made by: <%= @reservation.user.email %></p>
<br>
<p>You received 100 loyalty points! Check them out in your profile.</p>

<%= link_to "Back to restaurant", restaurant_path(@restaurant.id) %>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<% @restaurants.each do |restaurant| %>
  <a href="<%= restaurant_path(restaurant) %>"><%= restaurant.name %></a>
  <br>
<% end %>
<br>
<% if can? :create, Restaurant %>
  <%= link_to "Add a restaurant", new_restaurant_path %>
<% end %>

  

app/views/restaurants/new.html.erb
<div class="form-wrapper">
  <%= form_for @restaurant do |f| %>
    <% if @restaurant.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @restaurant.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :address %>
    <%= f.text_field :address %>
    <br>
    <%= f.label :neighbourhood %>
    <%= f.text_field :neighbourhood %>
    <br>
    <%= f.submit "Create", :class => "button" %>
  <% end %>
</div>
  

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>

<p> This restaurant was created by <%= @restaurant.user.email %> at <%= @restaurant.created_at %> </p>
<br>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@restaurant.latitude}%2C#{@restaurant.longitude}" %>

<hr>  
<%= link_to "Make a reservation", new_restaurant_reservation_path(@restaurant.id), :class => "button" %>
<hr>
<h3>Current reservations</h3>

<% @restaurant.reservations.each do |reservation| %>
  <% unless reservation.day.past? %>
    <p>Reservation for <%= reservation.guests %> at <%= reservation.time %> on <%= reservation.day %> <%= reservation.user.email %></p>
  <% end %>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Log in</h1>

<div class="form-wrapper">
  <%= form_tag user_sessions_path do %>
    <%= label_tag :email %>
    <%= text_field_tag :email %>
    <br>
    <%= label_tag :password %>
    <%= password_field_tag :password %>
    <br>
    <%= submit_tag "Log in", :class => "button" %>
  <% end %>
</div>
  

app/views/users/index.html.erb
<h1>This is the User index.</h1>

<%= link_to "Add a Restaurant", new_restaurant_path %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="form-wrapper">
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <div class="selector">
     <%= f.collection_select :role, User::ROLES, :to_s, :humanize %> 
    </div>
    <br>
    <%= f.submit "Sign up", :class => "button" %>
  <% end %>
</div>
  

app/views/users/show.html.erb
<h1>User!</h1>

<%= @user.email %>
<p>You have <%= @user.loyalty_points unless @user.loyalty_points.nil? %> loyalty points.</p>
<hr>
<h4>Your upcoming reservations:</h4>
<% @user.reservations.each do |reservation| %>
  <% unless reservation.day.past? %>
    <p>Reservation for <%= reservation.guests %> at <%= reservation.time %> on <%= reservation.day %> at <%= link_to reservation.restaurant.name, restaurant_path(reservation.restaurant_id) %></p>
  <% end %>
<% end %>

<!-- Users reservations -->
<% if @user.reservations.any? %>
  <hr>
  <h4>Your past reservations:</h4>
  <% @user.reservations.each do |reservation| %>
    <% if reservation.day.past? %>
      <section>
        <%= reservation.day.to_s(:short) %> at <%= reservation.time %> for <%= reservation.guests %> at <%= link_to reservation.restaurant.name, restaurant_path(reservation.restaurant_id) %>
      </section>
    <% end %>
  <% end %>
<% end %>

<!-- For Owners: This weeks reservations by restaurant -->
<% if can? :manage, Restaurant %>
  <hr>
  <h4>This weeks reservations at your restaurants:</h4>
  <% @user.restaurants.each do |restaurant| %>
    <h5><%= restaurant.name %></h5>
    <% restaurant.reservations.each do |reservation| %>
      <% if this_week?(reservation) %>
        <section>
          <%= reservation.guests %> at <%= reservation.time %> on <%= reservation.day %>
        </section>
      <% end %>
    <% end %>
    <hr>
  <% end %>
<% end %>

<!-- For Owners: Customer list -->
<% if can? :manage, Restaurant %>
  <h4>Your customers:</h4>
    <% your_customers(@user).each do |customer| %>
      <section>
        <%= customer.email %> has <%= customer.loyalty_points %>
      </section>
    <% end %>
<% end %>
<br>